import type { LocalModelEngineKind } from './types';

export {
    CHAT_MINIMUM_HISTORY_TURNS,
    CHAT_RESPONSE_TOKEN_RESERVE,
    HUGGING_FACE_BASE_URL,
    LANGUAGE_MODEL_TAG_BY_APP_LANGUAGE,
    LITERT_LM_CHAT_TEMPERATURE,
    LITERT_LM_CHAT_TOP_K,
    LITERT_LM_CHAT_TOP_P,
    LITERT_LM_CONSOLIDATION_TEMPERATURE,
    LITERT_LM_CONSOLIDATION_TOP_K,
    LITERT_LM_CONSOLIDATION_TOP_P,
    LITERT_LM_SAMPLING_SEED_LIMIT,
    NO_CHAT_MODEL_ID,
    OLLAMA_CONSOLIDATION_TOKEN_LIMIT,
    OLLAMA_MODEL_ID_PREFIX,
    OLLAMA_RESPONSE_TOKEN_LIMIT,
    REQUEST_STATUS_HISTORY_LIMIT,
} from '../../../../src/domains/llm/constants';

export const LLAMA_CPP_MODEL_ID_PREFIX = 'gguf:';
export const LLAMA_CPP_FILE_EXTENSION = '.gguf';
export const LLAMA_CPP_RESPONSE_TOKEN_LIMIT = 384;
export const LLAMA_CPP_CONSOLIDATION_TOKEN_LIMIT = 256;
export const LLAMA_CPP_DEFAULT_CONTEXT_WINDOW = 4096;
export const LLAMA_CPP_MINIMUM_CONTEXT_WINDOW = 512;
export const LLAMA_CPP_CONTEXT_WINDOW_STEP = 1024;
export const LLAMA_CPP_DOWNLOAD_PROTOCOLS: readonly string[] = ['http:', 'https:'];
export const LOCAL_MODEL_INSTALL_PREPARATION_IDS: Record<LocalModelEngineKind, string> = {
    llama_cpp: 'install:llama_cpp',
};
